### ISSUE TITLE
contracts docker build is failing on Mac machine - "memory access out of bounds"

### ISSUE THREAD

**Issue by levalleux-ludo** [bosonprotocol/core-components#568]
When building the docker container in ./contracts folder, the Solidity compiler is crashing, raising a "memory access out of bounds" exception

```
> [5/5] RUN npx hardhat compile:
0.649 Add submodulesContracts: [
0.649   '/app/protocol-contracts/submodules/seaport/contracts/Seaport.sol',
0.649   '/app/protocol-contracts/submodules/seaport/contracts/conduit/ConduitController.sol',
0.649   '/app/protocol-contracts/submodules/seaport/contracts/conduit/Conduit.sol'
0.649 ]
0.942 Downloading compiler 0.4.17
2.553 Downloading compiler 0.8.21
3.379 Downloading compiler 0.8.21
5.181 Downloading compiler 0.8.17
5.848 Downloading compiler 0.8.17
31.99 An unexpected error occurred:
31.99
31.99 RuntimeError: memory access out of bounds
31.99     at null.<anonymous> (wasm://wasm/05148d5e:1:234611)
31.99     at null.<anonymous> (wasm://wasm/05148d5e:1:158778)
31.99     at invoke_ii (/root/.cache/hardhat-nodejs/compilers-v2/wasm/soljson-v0.8.21+commit.d9974bed.js:110:37136)
31.99     at null.<anonymous> (wasm://wasm/05148d5e:1:19717525)
31.99     at ccall (/root/.cache/hardhat-nodejs/compilers-v2/wasm/soljson-v0.8.21+commit.d9974bed.js:110:28355)
31.99     at /root/.cache/hardhat-nodejs/compilers-v2/wasm/soljson-v0.8.21+commit.d9974bed.js:110:28746
31.99     at runWithCallbacks (/app/node_modules/hardhat/node_modules/solc/wrapper.js:151:24)
31.99     at compileStandard (/app/node_modules/hardhat/node_modules/solc/wrapper.js:207:14)
31.99     at Object.compileStandardWrapper [as compile] (/app/node_modules/hardhat/node_modules/solc/wrapper.js:214:14)
31.99     at Compiler.compile (/app/node_modules/hardhat/src/internal/solidity/compiler/index.ts:19:29)
------
Dockerfile:9
--------------------
   7 |     RUN npm ci
   8 |
   9 | >>> RUN npx hardhat compile
  10 |
  11 |     EXPOSE 8545
--------------------
ERROR: failed to solve: process "/bin/sh -c npx hardhat compile" did not complete successfully: exit code: 1
```

**Comment by levalleux-ludo** [comment]
https://pythonspeed.com/articles/docker-build-problems-mac/
